
name: Sync Repository Action
on:
  push:
  #schedule:
    # 每天北京时间0点同步
    #- cron:  '0 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: x-dr/sync-repo-to-gitee@master
      env:
          # 在 Settings->Secrets 配置 GITEE_KEY
          SSH_KEY: ${{ secrets.KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          github-repo: "git@github.com:toolslog/test.git"
          # 注意替换为你的 Gitee 目标仓库地址
          gitee-repo: "git@gitee.com:goindex/jdlxk.git"